
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
       # current_session_context_class: org.hibernate.context.internal.ThreadLocal‌​SessionContext
       # current_session_context_class: org.hibernate.context.internal.ThreadLocalSessionContext
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_second_level_cache: true
          use_query_cache: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blogdb
    username: root
    password: my-secret-pw

    remove-abandoned: true
    abandon-when-percentage-full: 80
    remove-abandoned-timeout: 600
    log-abandoned: true

    max-age: 10000
    min-idle: 5
    #max-idle: 10
    #max-active: 10

    initial-size: 20
    initialize: true






cors:
  allowed-origins-port: 3000
server:
  session:
    cookie:
      max-age: 300000



